services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    command:
      - start-dev
      - --verbose
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info,io.github.suengineering:trace
    ports:
      - "8080:8080"
    volumes:
      - ./target/keycloak-extension-oid4vp.jar:/opt/keycloak/providers/keycloak-extension-oid4vp.jar:ro
      - ./src/test/resources/realm-wallet-demo-local.json:/opt/keycloak/data/import/realm-wallet-demo-local.json:ro
